### ISSUE TITLE
Feature: check valid MX records for domain

### ISSUE THREAD

**Issue by 4n70w4** [inspheric/nova-email-field#5]
Users are not very smart and can make a mistake when entering emails, for example, specify a nonexistent domain. This can be verified by checking the MX records of the domain.

**Comment by kitbs** [comment]
Hi @4n70w4 

Thanks for the suggestion, but a feature like that doesn't belong in this package, which is just a UI/presentation component.

You might want to look at packages such as:
* https://github.com/tintnaingwinn/email-checker
* https://github.com/ddtraceweb/smtp-validator-email
* https://github.com/zytzagoo/smtp-validate-email

I haven't used these so I can't comment on them, but they seem to do what you are looking for.

It looks like some of them already come with a Laravel validation rule, but otherwise you could build your own custom validation rule. Then you would use it as:

```php
Email::make('Email')->rules(['email', 'your_custom_rule']);
```
